name: build and push
run-name: Build and push Python images to GHCR

on:
  push:
  schedule:
    - cron: 0 0 * * *
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Python Images
        run: |
          docker build . --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.12

      - name: Publish Python Images
        run: |
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.12
