name: build and push
run-name: Build and push Python images to GHCR

on:
  push:
  schedule:
    - cron: 0 0 * * *
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MAIN_BRANCH: "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Create Dockerfiles of Python Images
        run: python ./src/parse.py

      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          cmd: ls Python_dockerfiles
          separator: newline
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: Generated_Dockerfiles
          path: Python_dockerfiles/
          retention-days: 1
    outputs:
      param: ${{ steps.array.outputs.build }}

  matrix_input:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param: ${{ fromJson(needs.setup.outputs.param) }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Generated_Dockerfiles

      - name: building images
        run: docker build --file /${{matrix.param}}/Dockerfile --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}} .
      
      - name: Publishing images
        run: |
          tags = $(cat ${{matrix.param}}/tags.txt)
          IFS=$'\n'
          for tag in $tags; do
            docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:$tag
          done
      
      - name: delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: Generated_Dockerfiles