name: build and push
run-name: Build and push Python images to GHCR

on:
  push:
  schedule:
    - cron: 0 0 * * *
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:      

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Create Dockerfiles of Python Images
        run: python ./src/parse.py

      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          cmd: ls Python_dockerfiles
          separator: newline
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Generated_Dockerfiles
          path: Python_dockerfiles/
    outputs:
      param: ${{ steps.array.outputs.build }}

  matrix_input:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param: ${{ fromJson(needs.setup.outputs.param) }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Generated_Dockerfiles
      - run: |
          echo ${{matrix.param}}
          docker build --file ${{matrix.param}} --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{matrix.param}} .
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{matrix.param}}

