name: build and push
run-name: Build and push Python images to GHCR

on:
  push:
  schedule:
    - cron: 0 0 * * *
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Python Images
      run: |
        docker build . --target III.X --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.10
        docker build . --target III.XI --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.11
        docker build . --target III.XII --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.12
        docker build . --target latest --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest

    - name: Publish Python Images
      run: |
        docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.10
        docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.11
        docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:3.12
        docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
